name: .NET Core Build

on: push

jobs:
  Windows:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.300
      - name: Build for Windows 10/11. (x64)
        run: |
          cd Terminal
          dotnet publish -r win10-x64 -c Release /p:PublishSingleFile=true --self-contained true
      - name: Build for Windows 10/11. (x86)
        run: |
          cd Terminal
          dotnet publish -r win10-x86 -c Release /p:PublishSingleFile=true --self-contained true
      - name: Build for Windows 10/11. (ARM-64)
        run: |
          cd Terminal
          dotnet publish -r win10-arm64 -c Release /p:PublishSingleFile=true --self-contained true
      - name: Build for Windows 10/11. (ARM)
        run: |
          cd Terminal
          dotnet publish -r win10-arm -c Release /p:PublishSingleFile=true --self-contained true
      - name: Upload Windows 10/11. (x64)
        uses: actions/upload-artifact@v3
        with:
          name: stocknemo-win-x64
          path: Terminal/bin/Release/net6.0/win10-x64/publish/StockNemo.exe
      - name: Upload Windows 10/11. (x86)
        uses: actions/upload-artifact@v3
        with:
          name: stocknemo-win-x86
          path: Terminal/bin/Release/net6.0/win10-x86/publish/StockNemo.exe
      - name: Upload Windows 10/11. (ARM-64)
        uses: actions/upload-artifact@v3
        with:
          name: stocknemo-win-arm64
          path: Terminal/bin/Release/net6.0/win10-arm64/publish/StockNemo.exe
      - name: Upload Windows 10/11. (ARM)
        uses: actions/upload-artifact@v3
        with:
          name: stocknemo-win-arm
          path: Terminal/bin/Release/net6.0/win10-arm/publish/StockNemo.exe
          

  Linux:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.300
      - name: Build for Linux. (x64)
        run: |
          cd Terminal
          dotnet publish -r linux-x64 -c Release /p:PublishSingleFile=true --self-contained true
      - name: Build for Linux. (musl-x64)
        run: |
          cd Terminal
          dotnet publish -r linux-musl-x64 -c Release /p:PublishSingleFile=true --self-contained true
      - name: Build for Linux. (ARM)
        run: |
          cd Terminal
          dotnet publish -r linux-arm -c Release /p:PublishSingleFile=true --self-contained true
      - name: Build for Linux. (ARM-64)
        run: |
          cd Terminal
          dotnet publish -r linux-arm64 -c Release /p:PublishSingleFile=true --self-contained true
      - name: Upload Linux. (x64)
        uses: actions/upload-artifact@v3
        with:
          name: stocknemo-linux-x64
          path: Terminal/bin/Release/net6.0/linux-x64/publish/StockNemo
      - name: Upload Linux. (musl-x64)
        uses: actions/upload-artifact@v3
        with:
          name: stocknemo-linux-musl-x64
          path: Terminal/bin/Release/net6.0/linux-musl-x64/publish/StockNemo
      - name: Upload Linux. (ARM)
        uses: actions/upload-artifact@v3
        with:
          name: stocknemo-linux-arm
          path: Terminal/bin/Release/net6.0/linux-arm/publish/StockNemo
      - name: Upload Linux. (ARM-64)
        uses: actions/upload-artifact@v3
        with:
          name: stocknemo-linux-arm64
          path: Terminal/bin/Release/net6.0/linux-arm64/publish/StockNemo
          

  MacOS:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.300
      - name: Build for MacOS Mojave. (x64)
        run: |
          cd Terminal
          dotnet publish -r osx.10.14-x64 -c Release /p:PublishSingleFile=true --self-contained true
      - name: Build for MacOS Catalina. (x64)
        run: |
          cd Terminal
          dotnet publish -r osx.10.15-x64 -c Release /p:PublishSingleFile=true --self-contained true
      - name: Build for MacOS Big Sur. (x64)
        run: |
          cd Terminal
          dotnet publish -r osx.11.0-x64 -c Release /p:PublishSingleFile=true --self-contained true
      - name: Upload MacOS Mojave. (x64)
        uses: actions/upload-artifact@v3
        with:
          name: stocknemo-macos-mojave-x64
          path: Terminal/bin/Release/net6.0/osx.10.14-x64/publish/StockNemo
      - name: Upload MacOS Catalina. (x64)
        uses: actions/upload-artifact@v3
        with:
          name: stocknemo-macos-catalina-x64
          path: Terminal/bin/Release/net6.0/osx.10.15-x64/publish/StockNemo
      - name: Upload MacOS Big Sur. (x64)
        uses: actions/upload-artifact@v3
        with:
          name: stocknemo-macos-big-sur-x64
          path: Terminal/bin/Release/net6.0/osx.11.0-x64/publish/StockNemo
          
  Android:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.300
      - name: Build for Android (ALL VERSION COMPLIANT). (ARM-64)
        run: |
          cd Terminal
          dotnet publish -r android-arm64 -c Release /p:PublishSingleFile=true --self-contained true /p:UseAppHost=true
#      - name: Build for Android 32. (ARM-64)
#        run: |
#          cd Terminal
#          dotnet publish -r android.32-arm64 -c Release /p:PublishSingleFile=true --self-contained true /p:UseAppHost=true
#      - name: Build for Android 31. (ARM-64)
#        run: |
#          cd Terminal
#          dotnet publish -r android.31-arm64 -c Release /p:PublishSingleFile=true --self-contained true /p:UseAppHost=true
      - name: Upload Android (ALL VERSION COMPLIANT). (ARM-64)
        uses: actions/upload-artifact@v3
        with:
          name: stocknemo-android-all-arm64
          path: Terminal/bin/Release/net6.0/android-arm64/publish/StockNemo
#      - name: Upload Android 32. (ARM-64)
#        uses: actions/upload-artifact@v3
#        with:
#          name: stocknemo-android-32-arm64
#          path: Terminal/bin/Release/net6.0/android.32-arm64/publish/StockNemo
#      - name: Upload Android 31. (ARM-64)
#        uses: actions/upload-artifact@v3
#        with:
#          name: stocknemo-android-31-arm64
#          path: Terminal/bin/Release/net6.0/android.31-arm64/publish/StockNemo
    
#  iOS:
#    
#    runs-on: ubuntu-latest
#    
#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup .NET Core
#        uses: actions/setup-dotnet@v2
#        with:
#          dotnet-version: 6.0.300
#      - name: Build for iOS (ALL VERSION COMPLIANT). (ARM-64)
#        run: |
#          cd Terminal
#          dotnet publish -r ios-arm64 -c Release /p:PublishSingleFile=true --self-contained true /p:UseAppHost=true
#      - name: Build for iOS 15. (ARM-64)
#        run: |
#          cd Terminal
#          dotnet publish -r ios.15-arm64 -c Release /p:PublishSingleFile=true --self-contained true /p:UseAppHost=true
#      - name: Build for iOS 14. (ARM-64)
#        run: |
#          cd Terminal
#          dotnet publish -r ios.14-arm64 -c Release /p:PublishSingleFile=true --self-contained true /p:UseAppHost=true
#      - name: Upload iOS (ALL VERSION COMPLIANT). (ARM-64)
#        uses: actions/upload-artifact@v3
#        with:
#          name: stocknemo-ios-all-arm64
#          path: Terminal/bin/Release/net6.0/ios-arm64/publish/StockNemo
#      - name: Upload iOS 15. (ARM-64)
#        uses: actions/upload-artifact@v3
#        with:
#          name: stocknemo-ios-15-arm64
#          path: Terminal/bin/Release/net6.0/ios.15-arm64/publish/StockNemo
#      - name: Upload iOS 14. (ARM-64)
#        uses: actions/upload-artifact@v3
#        with:
#          name: stocknemo-ios-14-arm64
#          path: Terminal/bin/Release/net6.0/ios.14-arm64/publish/StockNemo