name: .NET Core Build

on: push

jobs:
  Build:
    strategy:
      matrix: 
        version: [4.0.0.0]
        configuration: [win10-x64, win10-x86, win10-arm64, win10-arm, linux-x64, linux-musl-x64, linux-arm, linux-arm64, osx.10.14-x64, osx.10.15-x64, osx.11.0-x64]
        include:
          - configuration: win10-x64
            file_extension: .exe
          - configuration: win10-x86
            file_extension: .exe
          - configuration: win10-arm64
            file_extension: .exe
          - configuration: win10-arm
            file_extension: .exe
        
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.300
      - name: Build for ${{ matrix.configuration }}
        run: |
          cd Terminal
          dotnet publish -r ${{ matrix.configuration }} -c Release /p:PublishSingleFile=true --self-contained true
          cd bin/Release/net6.0/${{ matrix.configuration }}/publish
          mv StockNemo${{ matrix.file_extension }} StockNemo-${{ matrix.version }}${{ matrix.file_extension }}
      - name: Upload binary for ${{ matrix.configuration }}
        uses: actions/upload-artifact@v3
        with:
          name: stocknemo-${{ matrix.configuration }}
          path: Terminal/bin/Release/net6.0/${{ matrix.configuration }}/publish/StockNemo-${{ matrix.version }}${{ matrix.file_extension }}