name: .NET Core Unit Test

on: push

jobs: 
  Main:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: Test
          report_name: stocknemo_unit_tests
          report_title: StockNemo Unit Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}